export const CITY_ERROR_CODES = {
  CITY_ALREADY_EXISTS: 'CITY_ALREADY_EXISTS',
  CITY_NOT_FOUND: 'CITY_NOT_FOUND',
  CITY_NAME_REQUIRED: 'CITY_NAME_REQUIRED',
  COUNTRY_ID_REQUIRED: 'COUNTRY_ID_REQUIRED',
  INVALID_CITY_NAME_LENGTH: 'INVALID_CITY_NAME_LENGTH',
  INVALID_COUNTRY_ID: 'INVALID_COUNTRY_ID',
  CITY_IN_USE: 'CITY_IN_USE',
  CITY_IN_USE_BY_PROVIDERS: 'CITY_IN_USE_BY_PROVIDERS',
  CITY_HAS_ACTIVE_PROVIDERS: 'CITY_HAS_ACTIVE_PROVIDERS',
  CITY_ALREADY_ACTIVE: 'CITY_ALREADY_ACTIVE',
  CITY_ALREADY_INACTIVE: 'CITY_ALREADY_INACTIVE',
} as const;

export type CityErrorCode =
  (typeof CITY_ERROR_CODES)[keyof typeof CITY_ERROR_CODES];
