export const CITY_ERROR_CODES = {
  CITY_ALREADY_EXISTS: 'CITY_ALREADY_EXISTS',
  CITY_NOT_FOUND: 'CITY_NOT_FOUND',
  CITY_NAME_REQUIRED: 'CITY_NAME_REQUIRED',
  COUNTRY_ID_REQUIRED: 'COUNTRY_ID_REQUIRED',
  INVALID_CITY_NAME_LENGTH: 'INVALID_CITY_NAME_LENGTH',
  INVALID_COUNTRY_ID: 'INVALID_COUNTRY_ID',
} as const;

export type CityErrorCode =
  (typeof CITY_ERROR_CODES)[keyof typeof CITY_ERROR_CODES];
