export const ADMIN_ERROR_CODES = {
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  EMAIL_ALREADY_IN_USE: 'EMAIL_ALREADY_IN_USE',
  INVALID_PERMISSION_TYPE: 'INVALID_PERMISSION_TYPE',
  INVALID_USER_TYPE: 'INVALID_USER_TYPE',
  INVALID_STATUS: 'INVALID_STATUS',
  CANNOT_DELETE_LAST_ADMINISTRATOR: 'CANNOT_DELETE_LAST_ADMINISTRATOR',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_OTP: 'INVALID_OTP',
  TOO_MANY_OTP_ATTEMPTS: 'TOO_MANY_OTP_ATTEMPTS',
  OTP_VERIFICATION_THROTTLED: 'OTP_VERIFICATION_THROTTLED',
  OTP_IP_MISMATCH: 'OTP_IP_MISMATCH',
  TOO_MANY_OTP_REQUESTS: 'TOO_MANY_OTP_REQUESTS',
} as const;