import { registerEnumType } from '@nestjs/graphql';

export enum ContractAuditAction {
  CONTRACT_CREATED = 'CONTRACT_CREATED',
  CONTRACT_RESENT = 'CONTRACT_RESENT',
  CONTRACT_ACCEPTED = 'CONTRACT_ACCEPTED',
  CONTRACT_REJECTED = 'CONTRACT_REJECTED',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  PROVIDER_COMPLETED = 'PROVIDER_COMPLETED',
  DELIVERY_STARTED = 'DELIVERY_STARTED',
  CUSTOMER_COMPLETED = 'CUSTOMER_COMPLETED',
  CANCELLATION_REQUESTED = 'CANCELLATION_REQUESTED',
  DELIVERY_REFUSED = 'DELIVERY_REFUSED',
  DISPUTE_REFUNDED = 'DISPUTE_REFUNDED',
  DISPUTE_RELEASED = 'DISPUTE_RELEASED',
  TIMEOUT_COMPLETED = 'TIMEOUT_COMPLETED',
  TIMEOUT_CANCELLED = 'TIMEOUT_CANCELLED',
}

registerEnumType(ContractAuditAction, {
  name: 'ContractAuditAction',
});
