export const RATING_ERROR_CODES = {
  RATING_NOT_FOUND: 'RATING_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ADVERTISEMENT_NOT_FOUND: 'ADVERTISEMENT_NOT_FOUND',
  DUPLICATE_RATING: 'DUPLICATE_RATING',
  INVALID_RATING_VALUE: 'INVALID_RATING_VALUE',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
} as const;

export type RatingErrorCode =
  (typeof RATING_ERROR_CODES)[keyof typeof RATING_ERROR_CODES];
