export const LISTING_ERROR_CODES = {
  LISTING_NOT_FOUND: 'LISTING_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CITY_NOT_FOUND: 'CITY_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_STATUS: 'INVALID_STATUS',
  PROVIDER_ONLY: 'PROVIDER_ONLY',
  LISTING_DELETED: 'LISTING_DELETED',
  LISTING_ALREADY_ACTIVE: 'LISTING_ALREADY_ACTIVE',
  LISTING_ALREADY_INACTIVE: 'LISTING_ALREADY_INACTIVE',
  LISTING_HAS_COMPLAINTS: 'LISTING_HAS_COMPLAINTS',
  LISTING_HAS_CONVERSATIONS: 'LISTING_HAS_CONVERSATIONS',
  LISTING_HAS_FAVORITES: 'LISTING_HAS_FAVORITES',
  LISTING_HAS_RATINGS: 'LISTING_HAS_RATINGS',
} as const;

export type ListingErrorCode =
  (typeof LISTING_ERROR_CODES)[keyof typeof LISTING_ERROR_CODES];
