export const LISTING_ERROR_CODES = {
  LISTING_NOT_FOUND: 'LISTING_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CITY_NOT_FOUND: 'CITY_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_STATUS: 'INVALID_STATUS',
  PROVIDER_ONLY: 'PROVIDER_ONLY',
  LISTING_DELETED: 'LISTING_DELETED',
} as const;

export type ListingErrorCode =
  (typeof LISTING_ERROR_CODES)[keyof typeof LISTING_ERROR_CODES];
