export const CONTRACT_ERROR_CODES = {
  CONTRACT_NOT_FOUND: 'CONTRACT_NOT_FOUND',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  INVALID_PRICE: 'INVALID_PRICE',
  INVALID_DOWN_PAYMENT: 'INVALID_DOWN_PAYMENT',
  DUPLICATE_CONTRACT: 'DUPLICATE_CONTRACT',
} as const;

export type ContractErrorCode =
  (typeof CONTRACT_ERROR_CODES)[keyof typeof CONTRACT_ERROR_CODES];
