export const CATEGORY_ERROR_CODES = {
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  PARENT_CATEGORY_NOT_FOUND: 'PARENT_CATEGORY_NOT_FOUND',
  INVALID_PARENT_CATEGORY: 'INVALID_PARENT_CATEGORY',
} as const;

export type CategoryErrorCode =
  (typeof CATEGORY_ERROR_CODES)[keyof typeof CATEGORY_ERROR_CODES];
