export const CATEGORY_ERROR_CODES = {
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  PARENT_CATEGORY_NOT_FOUND: 'PARENT_CATEGORY_NOT_FOUND',
  INVALID_PARENT_CATEGORY: 'INVALID_PARENT_CATEGORY',
  CATEGORY_HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',
  CATEGORY_IN_USE: 'CATEGORY_IN_USE',
  CATEGORY_IN_USE_BY_PROVIDERS: 'CATEGORY_IN_USE_BY_PROVIDERS',
  CATEGORY_ALREADY_ACTIVE: 'CATEGORY_ALREADY_ACTIVE',
  CATEGORY_ALREADY_INACTIVE: 'CATEGORY_ALREADY_INACTIVE',
} as const;

export type CategoryErrorCode =
  (typeof CATEGORY_ERROR_CODES)[keyof typeof CATEGORY_ERROR_CODES];
