export const NOTIFICATION_ERROR_CODES = {
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMPTY_TITLE: 'EMPTY_TITLE',
  EMPTY_MESSAGE: 'EMPTY_MESSAGE',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
} as const;

export type NotificationErrorCode =
  (typeof NOTIFICATION_ERROR_CODES)[keyof typeof NOTIFICATION_ERROR_CODES];
