export const CONVERSATION_ERROR_CODES = {
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  LISTING_NOT_FOUND: 'LISTING_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  DUPLICATE_CONVERSATION: 'DUPLICATE_CONVERSATION',
  CONVERSATION_HAS_CONTRACTS: 'CONVERSATION_HAS_CONTRACTS',
} as const;

export type ConversationErrorCode =
  (typeof CONVERSATION_ERROR_CODES)[keyof typeof CONVERSATION_ERROR_CODES];
