export const CONVERSATION_ERROR_CODES = {
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  ADVERTISEMENT_NOT_FOUND: 'ADVERTISEMENT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  DUPLICATE_CONVERSATION: 'DUPLICATE_CONVERSATION',
} as const;

export type ConversationErrorCode =
  (typeof CONVERSATION_ERROR_CODES)[keyof typeof CONVERSATION_ERROR_CODES];
