export const MESSAGE_ERROR_CODES = {
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  CONVERSATION_NOT_FOUND: 'CONVERSATION_NOT_FOUND',
  SENDER_NOT_FOUND: 'SENDER_NOT_FOUND',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  EMPTY_MESSAGE_CONTENT: 'EMPTY_MESSAGE_CONTENT',
  CHAT_FEE_REQUIRED: 'CHAT_FEE_REQUIRED',
  CONVERSATION_CLOSED: 'CONVERSATION_CLOSED',
} as const;

export type MessageErrorCode =
  (typeof MESSAGE_ERROR_CODES)[keyof typeof MESSAGE_ERROR_CODES];
