export const COMPLAINT_ERROR_CODES = {
  COMPLAINT_NOT_FOUND: 'COMPLAINT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ADVERTISEMENT_NOT_FOUND: 'ADVERTISEMENT_NOT_FOUND',
  REVIEWER_NOT_FOUND: 'REVIEWER_NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  EMPTY_DESCRIPTION: 'EMPTY_DESCRIPTION',
} as const;

export type ComplaintErrorCode =
  (typeof COMPLAINT_ERROR_CODES)[keyof typeof COMPLAINT_ERROR_CODES];
