export const ADMIN_PERMISSION_ERROR_CODES = {
  ADMIN_PERMISSION_NOT_FOUND: 'ADMIN_PERMISSION_NOT_FOUND',
  PERMISSION_ALREADY_ASSIGNED: 'PERMISSION_ALREADY_ASSIGNED',
  ADMIN_NOT_FOUND: 'ADMIN_NOT_FOUND',
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',
} as const;