export const PROVIDER_ERROR_CODES = {
  PROVIDER_NOT_FOUND: 'PROVIDER_NOT_FOUND',
  PROVIDER_ALREADY_EXISTS: 'PROVIDER_ALREADY_EXISTS',
  EMAIL_ALREADY_IN_USE: 'PROVIDER_EMAIL_ALREADY_IN_USE',
  PHONE_ALREADY_IN_USE: 'PROVIDER_PHONE_ALREADY_IN_USE',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  PHONE_NOT_VERIFIED: 'PHONE_NOT_VERIFIED',
  PROVIDER_DEACTIVATED: 'PROVIDER_DEACTIVATED',
  PROVIDER_SUSPENDED: 'PROVIDER_SUSPENDED',
  PROVIDER_REJECTED: 'PROVIDER_REJECTED',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  CONTRACT_ALREADY_SIGNED: 'CONTRACT_ALREADY_SIGNED',
  NO_SIGNED_CONTRACT: 'NO_SIGNED_CONTRACT',
  CONTRACT_ALREADY_TERMINATED: 'CONTRACT_ALREADY_TERMINATED',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  PROVIDER_ALREADY_ACTIVE: 'PROVIDER_ALREADY_ACTIVE',
  PLATFORM_MANAGER_SIGNATURE_MISSING: 'PLATFORM_MANAGER_SIGNATURE_MISSING',
} as const;

export type ProviderErrorCode =
  (typeof PROVIDER_ERROR_CODES)[keyof typeof PROVIDER_ERROR_CODES];
