export const ADVERTISEMENT_ERROR_CODES = {
  ADVERTISEMENT_NOT_FOUND: 'ADVERTISEMENT_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CITY_NOT_FOUND: 'CITY_NOT_FOUND',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  INVALID_PRICE: 'INVALID_PRICE',
} as const;

export type AdvertisementErrorCode =
  (typeof ADVERTISEMENT_ERROR_CODES)[keyof typeof ADVERTISEMENT_ERROR_CODES];
