import { registerEnumType } from '@nestjs/graphql';

export enum MessageKind {
  TEXT = 'TEXT',
  CONTRACT_CREATED = 'CONTRACT_CREATED',
  CONTRACT_ACCEPTED = 'CONTRACT_ACCEPTED',
  CONTRACT_REJECTED = 'CONTRACT_REJECTED',
  CONTRACT_RESENT = 'CONTRACT_RESENT',
  CONTRACT_PAID = 'CONTRACT_PAID',
  CONTRACT_PROVIDER_COMPLETED = 'CONTRACT_PROVIDER_COMPLETED',
  CONTRACT_DELIVERY_STARTED = 'CONTRACT_DELIVERY_STARTED',
  CONTRACT_CANCELLATION_REQUESTED = 'CONTRACT_CANCELLATION_REQUESTED',
  CONTRACT_DISPUTED = 'CONTRACT_DISPUTED',
  CONTRACT_CANCELLED = 'CONTRACT_CANCELLED',
  CONTRACT_COMPLETED = 'CONTRACT_COMPLETED',
  CHAT_FEE_PAID = 'CHAT_FEE_PAID',
}

registerEnumType(MessageKind, {
  name: 'MessageKind',
  description: 'User text or a typed system event in a conversation',
});
