import { registerEnumType } from '@nestjs/graphql';

export enum NotificationType {
  NEW_MESSAGE = 'NEW_MESSAGE',
  CONTRACT_CREATED = 'CONTRACT_CREATED',
  CONTRACT_SIGNED = 'CONTRACT_SIGNED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  ADVERTISEMENT_APPROVED = 'ADVERTISEMENT_APPROVED',
  ADVERTISEMENT_REJECTED = 'ADVERTISEMENT_REJECTED',
  NEW_RATING = 'NEW_RATING',
  COMPLAINT_SUBMITTED = 'COMPLAINT_SUBMITTED',
  COMPLAINT_RESOLVED = 'COMPLAINT_RESOLVED',
  SYSTEM_ANNOUNCEMENT = 'SYSTEM_ANNOUNCEMENT',
}

registerEnumType(NotificationType, {
  name: 'NotificationType',
  description: 'Type of notification',
});
