export const PERMISSION_ERROR_CODES = {
  PERMISSION_NOT_FOUND: 'PERMISSION_NOT_FOUND',
  PERMISSION_ALREADY_EXISTS: 'PERMISSION_ALREADY_EXISTS',
  INVALID_PERMISSION_PLATFORM: 'INVALID_PERMISSION_PLATFORM',
} as const;
