export const COUNTRY_ERROR_CODES = {
  COUNTRY_ALREADY_EXISTS: 'COUNTRY_ALREADY_EXISTS',
  COUNTRY_NOT_FOUND: 'COUNTRY_NOT_FOUND',
  CODE_ALREADY_IN_USE: 'CODE_ALREADY_IN_USE',
  INVALID_COUNTRY_CODE: 'INVALID_COUNTRY_CODE',
  COUNTRY_NAME_REQUIRED: 'COUNTRY_NAME_REQUIRED',
  COUNTRY_CODE_REQUIRED: 'COUNTRY_CODE_REQUIRED',
  INVALID_COUNTRY_NAME_LENGTH: 'INVALID_COUNTRY_NAME_LENGTH',
  INVALID_COUNTRY_CODE_LENGTH: 'INVALID_COUNTRY_CODE_LENGTH',
} as const;

export type CountryErrorCode =
  (typeof COUNTRY_ERROR_CODES)[keyof typeof COUNTRY_ERROR_CODES];
