export const FAVORITE_ERROR_CODES = {
  FAVORITE_NOT_FOUND: 'FAVORITE_NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ADVERTISEMENT_NOT_FOUND: 'ADVERTISEMENT_NOT_FOUND',
  DUPLICATE_FAVORITE: 'DUPLICATE_FAVORITE',
  UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
} as const;

export type FavoriteErrorCode =
  (typeof FAVORITE_ERROR_CODES)[keyof typeof FAVORITE_ERROR_CODES];
